export const eventInsights = {
  big_bang: "Why it matters: this is the starting point for every later story in the timeline. Space, matter, energy, and time become the raw material from which stars, planets, life, and eventually human history emerge.",
  earth_formation: "Why it matters: Earth is not simply a setting for history; it is a planet assembled by violence, cooling, chemistry, and chance. Its oceans, crust, and atmosphere become the narrow conditions that make life possible.",
  first_life: "Why it matters: the first cells turn chemistry into inheritance. Once life can copy itself, adapt, and alter its environment, Earth becomes a changing system rather than a static rock.",
  cambrian: "Why it matters: the Cambrian Explosion creates the basic animal architectures that still shape bodies today. Eyes, armor, predators, and nervous systems push evolution into a faster and more competitive phase.",
  great_dying: "Why it matters: mass extinction shows that progress is never guaranteed. The worst biological crisis in Earth's history clears ecological space for the lineages that later include dinosaurs and mammals.",
  dinosaurs: "Why it matters: dinosaurs prove how dominant a life form can become under the right conditions, and how quickly dominance can disappear. Their extinction opens the door for mammals to expand.",
  mammals: "Why it matters: mammal success is a lesson in opportunity after collapse. Small survivors fill empty niches, diversify, and eventually produce primates capable of culture and technology.",
  lucy: "Why it matters: upright walking changes the human story long before modern humans appear. It frees hands, shifts social behavior, and starts the slow separation between hominins and other apes.",
  ice_age: "Why it matters: climate pressure shapes migration, diet, tools, and survival strategies. The end of the Ice Age helps create the stable environment in which farming can begin.",
  fire: "Why it matters: fire is the first great human energy technology. It extends the day, protects communities, transforms food, and changes the biological economics of the human brain.",
  cavemen: "Why it matters: cave life reveals early humans as social, technical, and symbolic beings. Tools and marks on stone show that survival was already tied to memory, teaching, and imagination.",
  agriculture: "Why it matters: farming trades mobility for surplus. That surplus supports villages, hierarchy, taxation, specialized labor, armies, and nearly every institution later called civilization.",
  wheel: "Why it matters: the wheel turns muscle power into transport power. It reduces the cost of distance and lets goods, armies, and ideas move at scales earlier societies could not manage.",
  writing: "Why it matters: writing lets memory leave the human mind. Once records, contracts, laws, and stories can persist, states become larger and knowledge becomes cumulative.",
  pyramids: "Why it matters: the Great Pyramid is a monument to coordination as much as engineering. It shows how belief, administration, labor, and material science could be organized by the early state.",
  egypt: "Why it matters: Egypt demonstrates the power of geography. The Nile's predictability gives rulers the surplus and legitimacy needed to build a civilization that lasts for millennia.",
  babylon: "Why it matters: Hammurabi's code makes authority visible and portable. Written law does not end inequality, but it changes justice from personal command into public rule.",
  troy: "Why it matters: Troy sits between history and myth. Whether read as archaeology, epic memory, or political warning, it shows how war can outlive itself as cultural identity.",
  bronze_collapse: "Why it matters: the Bronze Age Collapse reveals the fragility of connected systems. Climate stress, migration, trade disruption, and warfare combine into a regional systems failure.",
  olympics: "Why it matters: the Olympic Games turn competition into shared identity. Athletics, religion, diplomacy, and prestige become a common language across rival Greek city-states.",
  rome_founding: "Why it matters: Rome's origin story shows how cities use myth to explain power. A small settlement becomes a political imagination capable of absorbing peoples and institutions.",
  democracy: "Why it matters: Athenian democracy proves that power can be organized through citizenship rather than inherited rank. Its limits were severe, but its ideas keep returning.",
  buddha: "Why it matters: Buddhism shifts attention from ritual status to suffering, discipline, and inner transformation. It becomes one of history's most durable alternatives to power-centered religion.",
  marathon: "Why it matters: Marathon gives Athens confidence at the exact moment democracy is still young. The victory becomes a political memory about freedom, citizenship, and resistance to empire.",
  alexander: "Why it matters: Alexander's conquests spread Greek language and institutions across older civilizations. The result is not simple conquest, but a hybrid Hellenistic world of exchange.",
  qin: "Why it matters: Qin unification shows the force of standardization. Shared scripts, measures, roads, and bureaucracy make China governable at an imperial scale.",
  caesar: "Why it matters: Caesar's assassination shows that killing a ruler does not necessarily restore a republic. When institutions are already weakened, political violence can accelerate collapse.",
  rome_empire: "Why it matters: the Roman Empire turns military victory into infrastructure, law, citizenship, and administration. Its institutions become a template that later powers repeatedly imitate.",
  jesus_birth: "Why it matters: Jesus begins as a marginal figure inside an occupied province, yet his movement later reshapes empire, ethics, art, timekeeping, and political legitimacy.",
  crucifixion: "Why it matters: the crucifixion transforms a Roman execution into a central religious symbol. It gives early Christianity a story of suffering, redemption, and moral reversal.",
  jerusalem: "Why it matters: the destruction of the Second Temple changes Judaism, Christianity, and Roman imperial policy. It turns a local revolt into a long historical rupture.",
  pompeii: "Why it matters: Pompeii is a disaster and an archive at once. Its sudden burial preserves ordinary urban life with a clarity most ancient cities never leave behind.",
  rome_fall: "Why it matters: Rome's fall is less a single collapse than a transfer of power. Western Europe loses imperial administration, while Roman law, Christianity, and memory continue shaping later kingdoms.",
  paper: "Why it matters: paper lowers the cost of recording thought. Cheaper writing changes bureaucracy, education, religion, trade, and eventually the speed of scientific communication.",
  zero: "Why it matters: zero turns absence into a number. That abstraction makes advanced calculation, algebra, accounting, engineering, and modern computing much easier to build.",
  islam: "Why it matters: Islam links faith, law, language, and empire into a powerful civilizational network. Its early expansion reshapes politics and scholarship across three continents.",
  charlemagne: "Why it matters: Charlemagne reconnects Western Europe after Rome's fragmentation. His empire fuses kingship, Christianity, education, and administration into a medieval model of rule.",
  vikings: "Why it matters: Viking expansion shows that mobility can be as decisive as numbers. Raids, trade, settlement, and exploration redraw Europe's political and economic map.",
  hastings: "Why it matters: Hastings changes England's ruling class, language, law, architecture, and relationship to continental Europe. One battle rewires an entire kingdom's future.",
  crusades: "Why it matters: the Crusades intensify contact and conflict between Christian and Muslim worlds. They reshape trade, violence, religious identity, and political authority around the Mediterranean.",
  mongols: "Why it matters: the Mongol Empire proves that steppe mobility can conquer settled states at continental scale. It also creates trade routes that move goods, people, disease, and knowledge.",
  black_death: "Why it matters: plague does more than kill; it changes labor markets, faith, medicine, and social trust. Europe's recovery is shaped by the shock of demographic collapse.",
  printing_press: "Why it matters: printing turns replication into a machine process. Once texts can spread cheaply and consistently, authority over knowledge becomes much harder to control.",
  constantinople: "Why it matters: Constantinople's fall ends a Roman continuity and redirects European ambition. Ottoman power, refugee scholars, and blocked trade routes help push Europe toward oceanic expansion.",
  columbus: "Why it matters: Columbus links the Atlantic worlds permanently, but the exchange is violently unequal. Trade, disease, conquest, and forced labor create the modern global system.",
  reformation: "Why it matters: the Reformation shows how media can destabilize institutions. Printed arguments turn theological dispute into a continent-wide crisis of authority.",
  scientific_rev: "Why it matters: the Scientific Revolution changes truth from inherited authority to testable evidence. Observation, measurement, and repeatable methods become tools for remaking the world.",
  pirates: "Why it matters: piracy exposes the violent underside of empire and trade. Wealth moving across oceans creates both state power and outlaw economies that feed on it.",
  industrial: "Why it matters: industrialization changes the basic unit of power from land to energy. Coal, machines, factories, and wage labor reorder cities, class, empire, and climate.",
  revolution: "Why it matters: the French Revolution makes politics ideological and mass-based. It proves that sovereignty can be claimed by the people, then weaponized by terror and war.",
  vaccine: "Why it matters: vaccination turns prevention into a public technology. It shows that medicine can protect populations, not just treat individuals after disease has arrived.",
  telephone: "Why it matters: the telephone collapses distance into real-time presence. Business, family life, emergency response, journalism, and diplomacy all change when voices travel instantly.",
  first_flight: "Why it matters: powered flight compresses geography. It changes war, travel, trade, migration, and the human sense of the planet's size.",
  titanic: "Why it matters: Titanic becomes a warning about technological confidence without adequate safety systems. Its loss forces changes in maritime regulation and emergency preparedness.",
  ww1: "Why it matters: World War I destroys old empires and faith in inevitable progress. Industrial technology, nationalism, and alliance politics create a new age of mass violence.",
  king_tut: "Why it matters: Tutankhamun's tomb turns archaeology into global spectacle. It also reveals how material culture can shape modern imagination about the ancient world.",
  television: "Why it matters: television makes public life visual and domestic. Politics, advertising, war, celebrity, and culture enter the living room at national scale.",
  ww2: "Why it matters: World War II reorganizes the global order. It produces the United Nations, decolonization pressure, the Cold War, nuclear deterrence, and new definitions of human rights.",
  computer: "Why it matters: electronic computing turns calculation into infrastructure. Once information can be processed automatically, science, government, finance, and daily life begin moving toward digital systems.",
  dna: "Why it matters: the DNA model gives life a readable code. Genetics becomes a way to understand inheritance, disease, identity, evolution, and biotechnology.",
  moon: "Why it matters: Apollo 11 turns geopolitics into a technical feat witnessed by the world. It shows what state capacity, science, risk, and ambition can do together.",
  voyager: "Why it matters: Voyager expands the scale of human presence. It is both an instrument and a message, carrying science outward and culture beyond the solar system.",
  smallpox: "Why it matters: smallpox eradication proves global cooperation can defeat an ancient enemy. It remains one of the clearest examples of public health at planetary scale.",
  challenger: "Why it matters: Challenger exposes the danger of normalizing risk inside complex institutions. The disaster becomes a case study in engineering culture and decision-making under pressure.",
  berlin_wall: "Why it matters: the fall of the Berlin Wall turns Cold War abstraction into human movement. It signals that regimes can appear permanent until legitimacy collapses quickly.",
  internet: "Why it matters: the web changes information from scarce and gatekept to searchable and networked. It creates new freedoms, new markets, and new forms of control.",
  dotcom_bubble: "Why it matters: the dot-com crash separates hype from infrastructure. The failed companies vanish, but the surviving networks and habits become the foundation of platform capitalism.",
  sept_11: "Why it matters: September 11 changes security, war, surveillance, immigration, and public fear. It marks a shift from Cold War geopolitics to asymmetric conflict and counterterrorism.",
  smartphone: "Why it matters: the smartphone makes the internet personal, portable, and constant. It reorganizes attention, work, memory, commerce, navigation, and social life around a handheld screen.",
  financial_crash: "Why it matters: the 2008 crash reveals how fragile financial engineering can become when risk is hidden. Its aftermath shapes inequality, regulation, politics, and trust in institutions.",
  mars_rover: "Why it matters: Curiosity turns Mars from a distant symbol into a studied environment. Robotic exploration lets humanity investigate other worlds before people arrive.",
  trillion_dollar_company: "Why it matters: Apple's trillion-dollar valuation signals a new concentration of economic power. Software, hardware, services, and user ecosystems begin rivaling old industrial giants.",
  covid: "Why it matters: COVID-19 shows how connected societies share risk. It tests public health, supply chains, trust, science communication, and the balance between individual freedom and collective safety.",
  ukraine: "Why it matters: the Ukraine war reopens questions many thought settled after 1991: borders, sovereignty, energy dependence, deterrence, alliances, and the durability of democratic resistance.",
  hormuz: "Why it matters: Hormuz is a reminder that geography still controls global systems. A narrow waterway can transmit regional conflict into worldwide energy, inflation, and security shocks."
};
